- name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Download Dobby Library
        run: |
          mkdir -p app/src/main/cpp/dobby
          git clone --depth 1 https://github.com/jmpews/Dobby.git app/src/main/cpp/dobby

      # 替换原来的 "Init Gradle Wrapper" 步骤
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.0 # 直接在此指定 Gradle 版本

      - name: Build APK
        run: |
          # 直接使用 gradle 命令，不再需要先生成 wrapper
          gradle :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FakeIO-Module
          path: app/build/outputs/apk/release/*.apk
